# Generated by Django 4.1.4 on 2023-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='student', max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('body', models.TextField(max_length=100)),
                ('lessons_time', models.CharField(max_length=70)),
                ('unpaid_time', models.IntegerField()),
                ('holydays', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
