# Generated by Django 4.1.4 on 2023-02-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lessons_time',
            new_name='lessons_times',
        ),
        migrations.AddField(
            model_name='student',
            name='single_lesson_time',
            field=models.IntegerField(default=60),
        ),
    ]
