# Generated by Django 4.1.4 on 2023-02-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_lessons_time_student_lessons_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='body',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='salary',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(default='Highschool', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='unpaid_time',
            field=models.IntegerField(default=0),
        ),
    ]
